package com.mcmcg.ico.bluefin;

public class BluefinWebPortalConstants {
	
	public static final String FULLDATEFORMAT = "YYYY-MM-dd HH:mm:ss.SSS";
	public static final String BATCHREPORTING = "BATCH_REPORTING";
	public static final String ADMINISTRATIVE = "ADMINISTRATIVE";
	public static final String PRODUCT_CONFIGURATION = "PRODUCT_CONFIGURATION";
	public static final String MANAGEALLUSERS = "MANAGE_ALL_USERS";
	public static final String USERNAME = "username";
	public static final String ID = "id";
	public static final String MANAGERESPONSECODES = "MANAGE_RESPONSE_CODES";
	public static final String PAYMENTPROCESSORINTERNALSTATUSCODEID = "PaymentProcessorInternalStatusCodeID";
	public static final String DATECREATED = "DateCreated";
	public static final String TRANSACTIONTIME = "TransactionTime";
	public static final String REMITTANCECREATIONDATE = "RemittanceCreationDate";
	public static final String REMITTANCECREATIONDATEBEGIN = "remittanceCreationDateBegin";
	public static final String REMITTANCECREATIONDATEEND = "remittanceCreationDateEnd";
	public static final String APPOCTSTREAM = "application/octet-stream";
	public static final String CONTENTDISPOSITION = "Content-Disposition";
	public static final String ATTACHMENTFILENAME = "attachment; filename=";
	public static final String TOKENHEADER = "TOKEN_HEADER";
	public static final String AUTHTOKENREQUIRERESOURCEMSG = "An authorization token is required to request this resource";
	public static final String USERINSUFFICIENTPERMISSIONMSG= "User does not have sufficient permissions for this profile.";
	public static final String CREATED = "created";
	public static final String PROCESSORNAME = "processorName";
	public static final String TRANSACTIONDATETIME = "transactionDateTime";
	public static final String PARAM1 = "Param1";
	public static final String AMOUNT = "amount";
	public static final String LEGALENTITY = "legalEntity";
	public static final String BATCHUPLOADID = "batchUploadId";
	public static final String PAYMENTFREQUENCY = "paymentFrequency";
	public static final String PAYMENTPROCESSORID = "paymentProcessorId";
	public static final String RECONCILIATIONSTATUSID = "reconciliationStatusId";
	public static final String REMITTANCECREATIONDATEVAL = "remittanceCreationDate";
	public static final String RESULT = "result";
	public static final String LIMIT = " LIMIT ";
	public static final String MAINSALE = "MAINSALE";
	public static final String SALEINNERREFUND = "SALEINNERREFUND";
	public static final String SALEINNERVOID = "SALEINNERVOID";
	public static final String REFUND = "REFUND";
	public static final String PAYMENTPROCESSORIDVAL = "PaymentProcessorID";
	public static final String PAYMENTPROCESSORREMITTANCEID = "PaymentProcessorRemittanceID";
	public static final String RECONCILIATIONSTATUSIDVAL = "ReconciliationStatusID";
	public static final String RECONCILIATIONDATE = "ReconciliationDate";
	public static final String PAYMENTMETHOD = "PaymentMethod";
	public static final String TRANSACTIONAMOUNT = "TransactionAmount";
	public static final String TRANSACTIONTYPE = "TransactionType";
	public static final String ACCOUNTIDVAL = "AccountID";
	public static final String APPLICATION = "Application";
	public static final String PROCESSORTRANSACTIONID = "ProcessorTransactionID";
	public static final String MERCHANTID = "MerchantID";
	public static final String TRANSACTIONSOURCE = "TransactionSource";
	public static final String FIRSTNAME = "FirstName";
	public static final String LASTNAME = "LastName";
	public static final String PROCESSORNAMEVAL = "ProcessorName";
	public static final String SALETRANSACTIONID = "SaleTransactionID";
	public static final String SALEFIRSTNAME = "SaleFirstName";
	public static final String SALELASTNAME = "SaleLastName";
	public static final String SALEPROCESSUSER = "SaleProcessUser";
	public static final String SALETRANSACTIONTYPE = "SaleTransactionType";
	
	public static final String SALEADDRESS1 = "SaleAddress1";
	public static final String SALEADDRESS2 = "SaleAddress2";
	public static final String SALECITY = "SaleCity";
	public static final String SALESTATE = "SaleState";
	public static final String SALEPOSTALCODE = "SalePostalCode";
	public static final String SALECOUNTRY = "SaleCountry";
	public static final String SALECARDNUMBERFIRST6CHAR = "SaleCardNumberFirst6Char";
	public static final String SALECARDNUMBERLAST4CHAR = "SaleCardNumberLast4Char";
	public static final String SALECARDTYPE = "SaleCardType";
	public static final String SALEEXPIRYDATE = "SaleExpiryDate";
	public static final String SALETOKEN = "SaleToken";
	public static final String SALECHARGEAMOUNT = "SaleChargeAmount";
	public static final String SALELEGALENTITYAPP = "SaleLegalEntityApp";
	public static final String SALEACCOUNTID = "SaleAccountId";
	public static final String SALEAPPLICATIONTRANSACTIONID = "SaleApplicationTransactionID";
	public static final String SALEMERCHANTID = "SaleMerchantID";
	public static final String SALEPROCESSOR = "SaleProcessor";
	public static final String SALEAPPLICATION = "SaleApplication";
	public static final String SALEORIGIN = "SaleOrigin";
	public static final String SALEPROCESSORTRANSACTIONID = "SaleProcessorTransactionID";
	public static final String SALETRANSACTIONDATETIME = "SaleTransactionDateTime";
	public static final String SALETESTMODE = "SaleTestMode";
	public static final String SALEAPPROVALCODE = "SaleApprovalCode";
	public static final String SALETOKENIZED = "SaleTokenized";
	public static final String SALEPAYMENTPROCESSORSTATUSCODE = "SalePaymentProcessorStatusCode";
	public static final String SALEPAYMENTPROCESSORSTATUSCODEDESCRIPTION = "SalePaymentProcessorStatusCodeDescription";
	public static final String SALEPAYMENTPROCESSORRESPONSECODE = "SalePaymentProcessorResponseCode";
	public static final String SALEPAYMENTPROCESSORRESPONSECODEDESCRIPTION = "SalePaymentProcessorResponseCodeDescription";
	public static final String SALEINTERNALSTATUSCODE = "SaleInternalStatusCode";
	public static final String SALEINTERNALSTATUSCODEDESCRIPTION = "SaleInternalStatusDescription";
	public static final String SALEINTERNALRESPONSECODE = "SaleInternalResponseCode";
	public static final String SALEINTERNALRESPONSECODEDESCRIPTION = "SaleInternalResponseDescription";
	public static final String SALEPAYMENTPROCESSORINTERNALSTATUSCODEID = "SalePaymentProcessorInternalStatusCodeID";
	public static final String SALEPAYMENTPROCESSORINTERNALRESPONSECODEID = "SalePaymentProcessorInternalResponseCodeID";
	public static final String SALEDATECREATED = "SaleDateCreated";
	public static final String SALEPAYMENTPROCESSORRULEID = "SalePaymentProcessorRuleID";
	public static final String SALERULEPAYMENTPROCESSORID = "SaleRulePaymentProcessorID";
	public static final String SALERULECARDTYPE = "SaleRuleCardType";
	public static final String SALERULEMAXIMUMMONTHLYAMOUNT = "SaleRuleMaximumMonthlyAmount";
	public static final String SALERULEMAXIMUMMONTHLYAMOUNTFLAG = "SaleRuleNoMaximumMonthlyAmountFlag";
	public static final String SALERULEPRIORITY = "SaleRulePriority";
	public static final String SALEACCOUNTPERIOD = "SaleAccountPeriod";
	public static final String SALEDESK = "SaleDesk";
	public static final String SALEINVOICENUMBER = "SaleInvoiceNumber";
	public static final String SALEUSERDEFINEDFIELD1 = "SaleUserDefinedField1";
	public static final String SALEUSERDEFINEDFIELD2 = "SaleUserDefinedField2";
	public static final String SALEUSERDEFINEDFIELD3= "SaleUserDefinedField3";
	public static final String SALERECONCILIATIONSTATUSID = "SaleReconciliationStatusID";
	public static final String SALERECONCILIATIONDATE = "SaleReconciliationDate";
	public static final String SALEBATCHUPLOADID = "SaleBatchUploadID";
	public static final String SALEISVOIDED = "SaleIsVoided";
	public static final String SALEISREFUNDED = "SaleIsRefunded";
	public static final String RECONCILIATIONSTATUSIDVAL1 = "ReconciliationStatus_ID";
	public static final String PROCESSORNAMEVAL1 = "Processor_Name";
	public static final String UNION = " UNION ";
	public static final String SALEVOIDREFUNDCONST = "0 AS SaleIsVoided,0 AS SaleIsRefunded,";
	public static final String CARDMASK = "XXXX-XXXX-XXXX-";
	public static final String VARCHAR = "VARCHAR";
	
	public static final String BLUEFIN_WEB_PORTAL_DATA_SOURCE = "bluefinDataSource";
	public static final String BLUEFIN_WEB_PORTAL_JDBC_TEMPLATE = "bluefinJdbcTemplate";
	public static final String BLUEFIN_BIN_DB_DATA_SOURCE = "binDBDataSource";
	public static final String BLUEFIN_BIN_DB_JDBC_TEMPLATE = "binJdbcTemplate";
	public static final String BLUEFIN_NAMED_JDBC_TEMPLATE = "bluefinNamedJdbcTemplate";
	public static final String BLUEFIN_ACCOUNT_VALIDATION_DATA_SOURCE = "bluefinAccountValidationDataSource";
	public static final String BLUEFIN_ACCOUNT_VALIDATION_JDBC_TEMPLATE = "bluefinAccountValidationJdbcTemplate";

	public static final String MATCHLASTPWCOUNT = "MATCH_LAST_PASSWORD_COUNT";
	public static final String PWEXPIREAFTER = "PASSWORD_EXPIRE_AFTER";
	public static final String PWEXPIREWARNBEFORE = "PASSWORD_EXPIRE_WARN_BEFORE";
	public static final String WRONGPWMAXLIMIT = "WRONG_PASSWORD_MAX_LIMIT";
	public static final int WRONGPASSWORDMAXLIMITDEFAULT = 6;
	public static final String ACCOUNTLOCKEDDURATIONSECONDS = "ACCOUNT_LOCKED_DURATION_SECONDS";
	public static final int ACCOUNTLOCKEDDURATIONSECONDSDEFAULT = 30*60;
	public static final int MATCHLASTPASSWORD = 4;
	public static final int PASSWORDEXPIREAFTERCOUNT = 90;
	public static final int PASSWORDEXPIREWARNBEFORECOUNT = 7;
	public static final String INVALIDLOGINATTEMPT = "INVALID LOGIN ACCESS ATTEMPT";
	public static final String SEPARATOR = " :: ";
	public static final String ADMINAUDITINFO = "ADMIN AUDIT INFO";
	public static final String REQUESTEDBY = "Requested By : ";
	public static final String REQUESTEDFOR = "Requested For : ";
	public static final String LEGALENTITYNAME = "Legal Entity Name : ";
	public static final String PAYMENTPROCESSORNAME = "Payment Processor Name : ";
	public static final String INTERNALCODEID = "Internal Code Id : ";
	public static final String PAYMENTPROCESSORIDLOG = "Payment Processor Id : ";
	public static final String APIUSER = "/api/users/";
	public static final String PASSLINK = "/password";
	public static final String WELCOMECONTENT = "Welcome to the Bluefin Portal.  Below is your username and a link to create a password. \n\n";
	public static final String CREATEPASSCONTENT = "\n\n To create your password, use the link below: \n\n";
	public static final String REGISTERUSEREMAIL = "REGISTER_USER_EMAIL_LINK";
	public static final String USERVALUE = "?user=";
	public static final String TOKENVALUE = "&token=";
	public static final Short ACTIVELEGALENTITY = 1;
	public static final String ACTIVESTATUS = "Is Legal Entity active : ";
	public static final String ACTIVEFORBATCHUPLOAD = "Is Legal Entity active for batch :";
	public static final String ACFAPPOCTSTREAM = "application/zip";
	public static final String SUCCESS = "success";
	public static final String DECLINED = "declined";
	public static final String ERROR = "error";
	public static final String BATCHRETURNFILENAMEFORACF = "Batch_Return_File_";
	public static final String TRANSACTIONREPORTPATH = "TRANSACTIONS_REPORT_PATH";
	public static final String CARDBRAND = "Credit";
	public static final String BATCH_UPLOAD_CARD_MASK = "xxxxxxxxxxxx";
	public static final String UPLOADED = "uploaded";
	public static final String BATCHRETURNFILES = "batch_return_file_";
	public static final String MCMLEGALENTITYNAMECONFIG = "MCM_LEGALENTITYNAME_CONFIG";
	public static final String ACFLEGALENTITYNAMECONFIG = "ACF_LEGALENTITYNAME_CONFIG";
	public static final String JPFLEGALENTITYNAMECONFIG = "JPF_LEGALENTITYNAME_CONFIG";
	public static final String MCMLEGALENTITYPREFIX = "MCM";
	public static final String ACFLEGALENTITYPREFIX = "ACF";
	public static final String JPFLEGALENTITYPREFIX = "JPF";
	public static final String MERCHANTIDPARAM = "merchantId";

	public static final String ACCOUNTSFILE = "file";
	public static final String IDSFILE = "fileIds";

	public static final String ACCOUNT_NUM= "accountNumber";
	public static final String TRANSACTION_ID= "transactionId";

	public static final String APPROVE_STATUS_CODE = "1";
	public static final String DECLINE_STATUS_CODE = "2";

	public static final String APPROVED_TRANSACTIONS_METRIC = "Approved Transactions";
	public static final String DECLINED_TRANSACTIONS_METRIC = "Declined Transactions";
	public static final String REPORT_PATH = "REPORT_PATH";

	private BluefinWebPortalConstants(){
		
	}
	
}
