package com.mcmcg.ico.bluefin;

public class BluefinWebPortalConstants {
	
	public static final String FULLDATEFORMAT = "YYYY-MM-dd HH:mm:ss.SSS";
	public static final String BATCHREPORTING = "BATCH_REPORTING";
	public static final String ADMINISTRATIVE = "ADMINISTRATIVE";
	public static final String MANAGEALLUSERS = "MANAGE_ALL_USERS";
	public static final String USERNAME = "username";
	public static final String ID = "id";
	public static final String MANAGERESPONSECODES = "MANAGE_RESPONSE_CODES";
	public static final String PAYMENTPROCESSORINTERNALSTATUSCODEID = "PaymentProcessorInternalStatusCodeID";
	public static final String DATECREATED = "DateCreated";
	public static final String TRANSACTIONTIME = "TransactionTime";
	public static final String REMITTANCECREATIONDATE = "RemittanceCreationDate";
	public static final String APPOCTSTREAM = "application/octet-stream";
	public static final String CONTENTDISPOSITION = "Content-Disposition";
	public static final String ATTACHMENTFILENAME = "attachment; filename=";
	public static final String TOKENHEADER = "TOKEN_HEADER";
	public static final String AUTHTOKENREQUIRERESOURCEMSG = "An authorization token is required to request this resource";
	public static final String USERINSUFFICIENTPERMISSIONMSG= "User does not have sufficient permissions for this profile.";
	public static final String CREATED = "created";
	public static final String PROCESSORNAME = "processorName";
	public static final String TRANSACTIONDATETIME = "transactionDateTime";
	public static final String PARAM1 = "Param1";
	public static final String AMOUNT = "amount";
	public static final String LEGALENTITY = "legalEntity";
	public static final String BATCHUPLOADID = "batchUploadId";
	public static final String PAYMENTFREQUENCY = "paymentFrequency";
	public static final String PAYMENTPROCESSORID = "paymentProcessorId";
	public static final String RECONCILIATIONSTATUSID = "reconciliationStatusId";
	public static final String REMITTANCECREATIONDATEVAL = "remittanceCreationDate";
	public static final String RESULT = "result";
	public static final String LIMIT = " LIMIT ";
	public static final String MAINSALE = "MAINSALE";
	public static final String SALEINNERREFUND = "SALEINNERREFUND";
	public static final String SALEINNERVOID = "SALEINNERVOID";
	public static final String REFUND = "REFUND";
	public static final String PAYMENTPROCESSORIDVAL = "PaymentProcessorID";
	public static final String PAYMENTPROCESSORREMITTANCEID = "PaymentProcessorRemittanceID";
	public static final String RECONCILIATIONSTATUSIDVAL = "ReconciliationStatusID";
	public static final String RECONCILIATIONDATE = "ReconciliationDate";
	public static final String PAYMENTMETHOD = "PaymentMethod";
	public static final String TRANSACTIONAMOUNT = "TransactionAmount";
	public static final String TRANSACTIONTYPE = "TransactionType";
	public static final String TRANSACTIONTIMEVAL = "TransactionTime";
	public static final String ACCOUNTIDVAL = "AccountID";
	public static final String APPLICATION = "Application";
	public static final String PROCESSORTRANSACTIONID = "ProcessorTransactionID";
	public static final String MERCHANTID = "MerchantID";
	public static final String TRANSACTIONSOURCE = "TransactionSource";
	public static final String FIRSTNAME = "FirstName";
	public static final String LASTNAME = "LastName";
	public static final String PROCESSORNAMEVAL = "ProcessorName";
	public static final String SALETRANSACTIONID = "SaleTransactionID";
	public static final String SALEFIRSTNAME = "SaleFirstName";
	public static final String SALELASTNAME = "SaleLastName";
	public static final String SALEPROCESSUSER = "SaleProcessUser";
	public static final String SALETRANSACTIONTYPE = "SaleTransactionType";
	
	public static final String SALEADDRESS1 = "SaleAddress1";
	public static final String SALEADDRESS2 = "SaleAddress2";
	public static final String SALECITY = "SaleCity";
	public static final String SALESTATE = "SaleState";
	public static final String SALEPOSTALCODE = "SalePostalCode";
	public static final String SALECOUNTRY = "SaleCountry";
	public static final String SALECARDNUMBERFIRST6CHAR = "SaleCardNumberFirst6Char";
	public static final String SALECARDNUMBERLAST4CHAR = "SaleCardNumberLast4Char";
	public static final String SALECARDTYPE = "SaleCardType";
	public static final String SALEEXPIRYDATE = "SaleExpiryDate";
	public static final String SALETOKEN = "SaleToken";
	public static final String SALECHARGEAMOUNT = "SaleChargeAmount";
	public static final String SALELEGALENTITYAPP = "SaleLegalEntityApp";
	public static final String SALEACCOUNTID = "SaleAccountId";
	public static final String SALEAPPLICATIONTRANSACTIONID = "SaleApplicationTransactionID";
	public static final String SALEMERCHANTID = "SaleMerchantID";
	public static final String SALEPROCESSOR = "SaleProcessor";
	public static final String SALEAPPLICATION = "SaleApplication";
	public static final String SALEORIGIN = "SaleOrigin";
	public static final String SALEPROCESSORTRANSACTIONID = "SaleProcessorTransactionID";
	public static final String SALETRANSACTIONDATETIME = "SaleTransactionDateTime";
	public static final String SALETESTMODE = "SaleTestMode";
	public static final String SALEAPPROVALCODE = "SaleApprovalCode";
	public static final String SALETOKENIZED = "SaleTokenized";
	public static final String SALEPAYMENTPROCESSORSTATUSCODE = "SalePaymentProcessorStatusCode";
	public static final String SALEPAYMENTPROCESSORSTATUSCODEDESCRIPTION = "SalePaymentProcessorStatusCodeDescription";
	public static final String SALEPAYMENTPROCESSORRESPONSECODE = "SalePaymentProcessorResponseCode";
	public static final String SALEPAYMENTPROCESSORRESPONSECODEDESCRIPTION = "SalePaymentProcessorResponseCodeDescription";
	public static final String SALEINTERNALSTATUSCODE = "SaleInternalStatusCode";
	public static final String SALEINTERNALSTATUSCODEDESCRIPTION = "SaleInternalStatusDescription";
	public static final String SALEINTERNALRESPONSECODE = "SaleInternalResponseCode";
	public static final String SALEINTERNALRESPONSECODEDESCRIPTION = "SaleInternalResponseDescription";
	public static final String SALEPAYMENTPROCESSORINTERNALSTATUSCODEID = "SalePaymentProcessorInternalStatusCodeID";
	public static final String SALEPAYMENTPROCESSORINTERNALRESPONSECODEID = "SalePaymentProcessorInternalResponseCodeID";
	public static final String SALEDATECREATED = "SaleDateCreated";
	public static final String SALEPAYMENTPROCESSORRULEID = "SalePaymentProcessorRuleID";
	public static final String SALERULEPAYMENTPROCESSORID = "SaleRulePaymentProcessorID";
	public static final String SALERULECARDTYPE = "SaleRuleCardType";
	public static final String SALERULEMAXIMUMMONTHLYAMOUNT = "SaleRuleMaximumMonthlyAmount";
	public static final String SALERULEMAXIMUMMONTHLYAMOUNTFLAG = "SaleRuleNoMaximumMonthlyAmountFlag";
	public static final String SALERULEPRIORITY = "SaleRulePriority";
	public static final String SALEACCOUNTPERIOD = "SaleAccountPeriod";
	public static final String SALEDESK = "SaleDesk";
	public static final String SALEINVOICENUMBER = "SaleInvoiceNumber";
	public static final String SALEUSERDEFINEDFIELD1 = "SaleUserDefinedField1";
	public static final String SALEUSERDEFINEDFIELD2 = "SaleUserDefinedField2";
	public static final String SALEUSERDEFINEDFIELD3= "SaleUserDefinedField3";
	public static final String SALERECONCILIATIONSTATUSID = "SaleReconciliationStatusID";
	public static final String SALERECONCILIATIONDATE = "SaleReconciliationDate";
	public static final String SALEBATCHUPLOADID = "SaleBatchUploadID";
	public static final String SALEISVOIDED = "SaleIsVoided";
	public static final String SALEISREFUNDED = "SaleIsRefunded";
	public static final String RECONCILIATIONSTATUSIDVAL1 = "ReconciliationStatus_ID";
	public static final String PROCESSORNAMEVAL1 = "Processor_Name";
	public static final String UNION = " UNION ";
	
	private BluefinWebPortalConstants(){
		
	}
	
}
